### ISSUE TITLE
Dns resolve did not respond within 5.000 s

### ISSUE THREAD

**Issue by shanmukha511** [kubernetes/dns#376] opened 2020-04-21 08:16 UTC
Hi Team,

Getting below error . Did anyone has faced this error?
Dns resolve did not respond within 5.000 s

How to fix this issue?

**Comment by aojea** [comment] 2020-04-23 13:44
/close

This is a duplicate of https://github.com/kubernetes/kubernetes/issues/90369

**Closed** 2020-04-23 13:55 UTC
