### ISSUE TITLE
kube-dns crashing on GKE 1.9.2 (panic: counter cannot decrease in value)

### ISSUE THREAD

**Issue by Stono** [kubernetes/dns#195] opened 2018-02-08 21:09 UTC
See the title really, the sidecar pod is crashing every few minutes on the recent release GKE 1.9.2 release:

```
❯ kks logs kube-dns-6cdf767cb8-ht7fr -p sidecar
I0208 20:59:53.889088       1 main.go:51] Version v1.14.8
I0208 20:59:53.889223       1 server.go:45] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 Probes:[{Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33} {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}] PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:kubedns})
I0208 20:59:53.889281       1 dnsprobe.go:75] Starting dnsProbe {Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}
I0208 20:59:53.889359       1 dnsprobe.go:75] Starting dnsProbe {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}
panic: counter cannot decrease in value

goroutine 1 [running]:
k8s.io/dns/vendor/github.com/prometheus/client_golang/prometheus.(*counter).Add(0xc42040ef40, 0xc062c00000000000)
        /go/src/k8s.io/dns/vendor/github.com/prometheus/client_golang/prometheus/counter.go:71 +0xa7
k8s.io/dns/pkg/sidecar.exportMetrics(0xc420156150)
        /go/src/k8s.io/dns/pkg/sidecar/server.go:86 +0x1c3
k8s.io/dns/pkg/sidecar.(*server).runMetrics(0xc420234c90, 0xc4202ec3f0)
        /go/src/k8s.io/dns/pkg/sidecar/server.go:68 +0x1d6
k8s.io/dns/pkg/sidecar.(*server).Run(0xc420234c90, 0xc4202ec3f0)
        /go/src/k8s.io/dns/pkg/sidecar/server.go:53 +0x244
main.main()
        /go/src/k8s.io/dns/cmd/sidecar/main.go:56 +0x209
```

**Comment by ace-subido** [comment] 2018-03-02 10:53
Same error log here, Stackdriver reports the same error log. Also our kube-dns pods are crashing every few minutes. We're also running the 1.9.2-gke.1 release. 

Looking over at Google Console, the `kube-system -> sidecar` logs shows this:

```
Error getting metrics from dnsmasq: read udp 127.0.0.1:35611->127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: read udp 127.0.0.1:34554->127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: read udp 127.0.0.1:45017->127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: dial udp 127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: dial udp 127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: dial udp 127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: dial udp 127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: read udp 127.0.0.1:48731->127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: read udp 127.0.0.1:53758->127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: read udp 127.0.0.1:38708->127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: read udp 127.0.0.1:52629->127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: dial udp 127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: dial udp 127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: dial udp 127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: read udp 127.0.0.1:59812->127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: read udp 127.0.0.1:38446->127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: dial udp 127.0.0.1:53: i/o timeout 
Error getting metrics from dnsmasq: read udp 127.0.0.1:37408->127.0.0.1:53: i/o timeout 
```

**Comment by MrHohn** [comment] 2018-03-02 19:24
cc @rramkumar1 possibly introduced by https://github.com/kubernetes/dns/pull/173?

**Comment by rramkumar1** [comment] 2018-03-02 21:34
@Stono What's happening is that when the dnsmasq container gets restarted (on a ConfigMap change), the metrics get reset and we end up reducing the prometheus counter in the sidecar. This is exactly the error you were getting. We were able to systematically reproduce the issue and we are confident that this should not affect your cluster for the time being. Specifically, the sidecar container should panic, get restarted and function properly. However, we are going to look into a more long term fix for this and hopefully push it in the next kube-dns release.

@ace-subido Your kube-dns pod should not be crashing because of this. Could you possibly provide some more information? Looking at those logs you provided, it seems like the sidecar's requests to dnsmasq are timing out, which would coincide with dnsmasq getting restarted due to the reason stated above.

**Comment by ctlam** [comment] 2018-03-09 19:13
I have the exactly problem too, and the kube-dns is crashing every minute:

**kubectl get po --namespace=kube-system -o wide |grep dns**
kube-dns-79d99cdcd5-knc5n              1/3       CrashLoopBackOff   20         20m   


**kubectl  --namespace=kube-system logs kube-dns-79d99cdcd5-knc5n sidecar**

I0309 19:01:25.817062       1 main.go:51] Version v1.14.8
I0309 19:01:25.817161       1 server.go:45] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 Probes:[{Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1} {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}] PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:kubedns})
I0309 19:01:25.817189       1 dnsprobe.go:75] Starting dnsProbe {Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}
I0309 19:01:25.817255       1 dnsprobe.go:75] Starting dnsProbe {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}
panic: counter cannot decrease in value

goroutine 1 [running]:
k8s.io/dns/vendor/github.com/prometheus/client_golang/prometheus.(*counter).Add(0xc4203e8580, 0xc052c00000000000)
        /go/src/k8s.io/dns/vendor/github.com/prometheus/client_golang/prometheus/counter.go:71 +0xa7
k8s.io/dns/pkg/sidecar.exportMetrics(0xc4201841e8)
        /go/src/k8s.io/dns/pkg/sidecar/server.go:86 +0x1c3
k8s.io/dns/pkg/sidecar.(*server).runMetrics(0xc4201e4690, 0xc420206af0)
        /go/src/k8s.io/dns/pkg/sidecar/server.go:68 +0x1d6
k8s.io/dns/pkg/sidecar.(*server).Run(0xc4201e4690, 0xc420206af0)
        /go/src/k8s.io/dns/pkg/sidecar/server.go:53 +0x244
main.main()
        /go/src/k8s.io/dns/cmd/sidecar/main.go:56 +0x209

**Comment by ctlam** [comment] 2018-03-09 19:55
Here is what I found out and made the problem go away:

It turned out the other node (say: node2) that ran the other kubedns pod (pod2) had gone from "Ready" to "Not Ready" (for unknown reason).  The other pod didn't report problem though.  I restarted the kubelet service on the node2 (without restarting any pod on it).   Then, the above problem (pod1 on node1) went away.

**Comment by miks** [comment] 2018-05-24 19:46
@rramkumar1 I have same problem as @ace-subido.
As kube-dns is crashing all the time, DNS resolving is not working on all other pods.
I have only one node with kube-dns version 1.14.8.
On other cluster I have kube-dns version 1.14.5 with no such DNS problem.

I can provide more information, just let me know.

**Comment by miks** [comment] 2018-05-24 20:50
After further investigation found that Ubuntu 18.04 new "systemd-resolved" DNS service was to blame.
More at https://github.com/kubernetes/kubernetes/issues/49411#issuecomment-318780912
I fixed by deleting /etc/resolver.conf symlink and recreating new /etc/resolver.conf with my network router DNS.

**Comment by 372046933** [comment] 2018-05-29 02:29
The same promblem affected me. Restart kubelet does not work

**Comment by lavalamp** [comment] 2018-08-03 02:39
I observe this on one of my clusters. Sidecar Version v1.14.8.3, Kubernetes 1.9.7. Seems harmless enough, I guess.

**Closed** 2018-12-31 04:39 UTC
Labels: lifecycle/rotten, sig/gcp
