### ISSUE TITLE
Question: node-local-dns metrics stopped working after upgrading to EKS 1.20

### ISSUE THREAD

**Issue by rivlinpereira** [kubernetes/dns#506] opened 2022-01-27 18:11 UTC
Hi,

Has anyone seen issues with metrics stop reporting when upgrading to eks 1.20 from eks 1.19 for nodelocaldns? We monitor for metrics like `nodelocaldns request latency (99/95/avg)` `nodelocaldns rcode count - noerror` `nodelocal healthcheck failures` `nodelocaldns request count` and they all stopped reporting metrics after we upgraded.

I turned on logs in node-local-dns config map to look at the queries and we dont any issues there. Also on smaller clusters with 3 nodes we dont see this, only on clusters with 50 plus nodes we are seeing this issue. We also updated the node-local-dns docker image to 1.20.0 and still no metrics. We do also have calico running in the cluster.

Any pointers on this would be appreciated

**Comment by prameshj** [comment] 2022-01-27 21:08
You can try "curl http://<nodelocaldnsip>:9253/metrics" to see if metrics are exported by the pod. If yes, then the issue is somewhere in the layer that exports it up.

**Comment by rivlinpereira** [comment] 2022-01-27 21:59
I do see that they are exported, the strange part if on the cluster where i see metrics coming in the /metrics endpoint does not work on the pod. I will look in more.

**Comment by prameshj** [comment] 2022-02-01 19:12
Thanks! Closing since this is resolved.

**Closed by prameshj** 2022-02-01 19:12 UTC
