### ISSUE TITLE
Reload plugin not working on k8s-dns-node-cache

### ISSUE THREAD

**Issue by semoac** [kubernetes/dns#356] opened 2020-03-14 18:14 UTC
Hi.

I notice that, on k8s-dns-node-cache, `/etc/Corefile` isn't updated when  `/etc/coredns/Corefile.base` changes, making the `reload` plugins useless.

I'm using `k8s.gcr.io/k8s-dns-node-cache:1.15.10`.

Cheers!

**Comment by prameshj** [comment] 2020-04-18 06:31
Does update happen if the node-local-dns configmap changes? I have verified this to be working.

Another way to trigger a reload is by configuring stubDomains via kube-dns configmap[1] , node-cache automatically picks those up. It can take a minute or so for the config to be updated.

[1] https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configure-stub-domain-and-upstream-dns-servers

**Comment by prameshj** [comment] 2020-07-01 19:53
Closing since there hasn't been a response.. please reopen if needed.

**Closed by prameshj** 2020-07-01 19:53 UTC

**Comment by owengo** [comment] 2020-07-22 14:35
I'm using k8s.gcr.io/k8s-dns-node-cache:1.15.10 also,
the issue is that when we edit the config-map node-local-dns  - which is mounted as /etc/coredns/Corefile.base - the /etc/Corefile is not re-generated and the configuration is not reloaded.
Even sending SIGHUP / SIGUSR1 does not work because /etc/Corefile is reloaded but not re-generated from the Corefile.base template.

Your workaround of editing the old kube-dns configmap works. It would be more practical  if the process could detect changes in /etc/coredns/Corefile.base.

**Comment by prameshj** [comment] 2020-07-22 14:42
This should be fixed with https://github.com/kubernetes/dns/pull/377

can you try with 1.15.13 image?
